Transform unary expressions that mutate private names
mheiber/TypeScript pull request #8
Opened 2018-08-20 21:09 UTC by joeywatts

2018-08-20 22:03 UTC, mheiber requested changes

2018-08-20 22:03 UTC, mheiber commented on src/compiler/transformers/esnext.ts
>                      return visitObjectLiteralExpression(node as ObjectLiteralExpression);
could you add a test case? It would be helpful, since I don't have a good intuition about what kinds of code this will generate yet.

2018-08-21 20:07 UTC, joeywatts commented on tests/baselines/reference/propertyUnaryMutation.js
> +        _classPrivateFieldSet(this, _property, ((_a = _classPrivateFieldGet(this, _property)) + 1, _a));
Whoops, just realized that I did this backwards... I will fix 😂

2018-08-21 22:10 UTC, joeywatts commented
Going to reopen this against the new branch on my repo

2018-08-21 22:10 UTC, closed without merging